language: php

dist: xenial

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

env:
    - COMPOSER_NO_INTERACTION=1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer install --no-scripts --no-suggest

script:
    - composer validate --strict
    - find src/ examples/ tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 php -l
    - vendor/bin/phpunit

before_deploy:
    - sed -e "/const CLIENT_VERSION/c\\ const CLIENT_VERSION = '${TRAVIS_TAG:1}';" -i src/ApiClient.php
    - make spikkl-php-client.zip

deploy:
    provider: releases
    api_key:
        secure: "ZR+PfWBJpf6ObF00707ybdO23V1FVUtw9QqYFNvMbqXR0eCn0o60zNLc/nCHo7wwWRgI11NzLDQc0IVKv00Hb//DAleW2v1F0Ba04rqGtk3QzaNyReW9YI+xOgAfK7NHwJWW7hthsnwXgCX3NRST/Aa2xXzfpQlvcjVTB4OK0V0p9I8Bnvv1JhdUeMQ6EZiLx0NW9B08pukYJtby54P3NpE9Tm04oG7FHlB+CumYOqYISin65rYpHmVNSzb+OS+7j6QxKabS46fqVQathkfyno0NEJpzHwhtseUD1X2V1XUNwXaKYCprsP2eSfJSH18Z1LCeox0VKrNRhfbrThR6UIrtzSFSPAqsgxJpzKx7lzmLy2sGR9xlw3NXkKVtLtUVHmJY9qYrDvkqWqZXn8yX5vzs0adb2+81GQMoGOOETNBV8ljI4WxdfVBBJjzQUkTCVUDoQI5m1XWViaCIVqsOE7wqYLsfnFr25IUk57302eK8whL45X8AuUQ7Z/Jwc1WbOx6U60pTEzcy+lN4HabTiefq9+4kIGFGcLixU/e26ulCNy22raHAHb2NVgYVOGrkfLkJPDT7BWCm79ptwhvB4VjQ1lKLAG6VZuz3m5VvemC1L5WMPZqnIyPNBNng3i0hdTk9Zcn6dIDhkaIvz0VZ0xVdxqt99X5Kx3tLkCOlBNw="
    file: spikkl-php-client.zip
    skip_cleanup: true
    on:
        tags: true
        php: 7.2